# create your custom drupal image here, based of official drupal
FROM ubuntu:latest

RUN apt-get update && apt-get install -y git curl wget iperf traceroute inetutils-ping \
    && rm -rf /var/lib/apt/lists/*
